---
- hosts: tiuraniemi.org
  become: true
  become_user: root
  tasks:
      - name: Update apt repo and cache
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

      - name: Upgrade all debian packages
        apt: upgrade=dist force_apt_get=yes

      - name: Upgrade virtualenv
        pip:
            name: virtualenv
            extra_args: --upgrade

      - name: Check if a reboot is needed
        register: reboot_required_file
        stat: path=/var/run/reboot-required get_md5=no

      - name: Reboot if kernel updated
        reboot:
            msg: 'Reboot initiated by Ansible for kernel updates'
            connect_timeout: 5
            reboot_timeout: 300
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: uptime
        when: reboot_required_file.stat.exists
